# 1. 베이스 이미지 설정
FROM node:20-alpine

# 2. 작업 디렉토리 설정
WORKDIR /home/node/app

# 3. 필요한 파일 복사
COPY backend ./backend
COPY interface ./interface

# 4. Corepack 활성화 (Pnpm 지원)
RUN corepack enable

# 5. 의존성 설치 (백엔드)
WORKDIR /home/node/app/backend
RUN pnpm install --frozen-lockfile && pnpm prisma generate

# 6. 의존성 설치 (프론트엔드)
WORKDIR /home/node/app/interface
RUN pnpm install --frozen-lockfile

# 7. 백엔드 빌드
WORKDIR /home/node/app/backend
RUN pnpm build

# 8. 실행 명령 설정
CMD ["node", "dist/main.js"]
